{"name": "Логин с невалидными данными", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/89.0.3987.106/chromedriver_linux64.zip", "trace": "@pytest.fixture()\n    def driver():\n>       driver = driver_init()\n\nconftest.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconftest.py:18: in driver_init\n    driver = webdriver.Chrome(ChromeDriverManager('89.0.3987.106').install())\n../../.local/lib/python3.6/site-packages/webdriver_manager/chrome.py:24: in install\n    driver_path = self.download_driver(self.driver)\n../../.local/lib/python3.6/site-packages/webdriver_manager/manager.py:39: in download_driver\n    path = self.__download_and_save_driver_to_cache(driver, driver_version)\n../../.local/lib/python3.6/site-packages/webdriver_manager/manager.py:27: in __download_and_save_driver_to_cache\n    response = download_driver(driver.get_url(driver_version))\n../../.local/lib/python3.6/site-packages/webdriver_manager/utils.py:55: in download_driver\n    validate_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    def validate_response(resp):\n        if resp.status_code == 404:\n>           raise ValueError(\"There is no such driver by url {}\".format(resp.url))\nE           ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/89.0.3987.106/chromedriver_linux64.zip\n\n../../.local/lib/python3.6/site-packages/webdriver_manager/utils.py:40: ValueError"}, "attachments": [{"name": "stdout", "source": "dc71aeb3-6f4c-40a4-8aac-27ca13af2a56-attachment.txt", "type": "text/plain"}], "start": 1587198594469, "stop": 1587198594469, "uuid": "4f538ecf-9c3f-4745-8617-691417da35b1", "historyId": "96ba6f3287c51884614891c52db82d3a", "testCaseId": "a870091396398a27235873ce8a4288eb", "fullName": "tests.test_1_login#test_pkm_login_invalid", "labels": [{"name": "story", "value": "Логин админом"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Логин/Логаут"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "host", "value": "Vostro-3559"}, {"name": "thread", "value": "9328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_1_login"}]}